%% Dataset Modifiche Finali

for i=47:48
        Tabella(i,1).acc_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,2).acc_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,3).acc_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,4).gyro_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,5).gyro_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,6).gyro_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,7).mag_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,8).mag_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,9).mag_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,10).vel_x_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,11).vel_y_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,12).vel_z_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,13).vel_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,14).vel_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,15).vel_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,16).atm_press{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,17).gps_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,18).gps_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,19).gps_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,20).wind_x{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,21).wind_y{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,22).wind_z{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,23).IMU_temp{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,24).roll{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,25).roll_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,26).pitch{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,27).pitch_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,28).yaw{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,29).yaw_des{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,30).ch1{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,31).ch2{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,32).ch3{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,33).ch4{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,34).ch5{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,35).ch6{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,36).ch7{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,37).ch8{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,38).err_track{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,39).err_speed{1}.Properties.DimensionNames{1} = 'timestamp';
        Tabella(i,40).err_alt{1}.Properties.DimensionNames{1} = 'timestamp';
end
