version: '3.7'
services:
    dbpg:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes: 
          # copy the sql script to create tables
          - ./scripts/full.sql:/docker-entrypoint-initdb.d/full.sql         
    nodeapp:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env
        depends_on:
          - dbpg